# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_RasterToolkit', [dirname(__file__)])
        except ImportError:
            import _RasterToolkit
            return _RasterToolkit
        if fp is not None:
            try:
                _mod = imp.load_module('_RasterToolkit', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _RasterToolkit = swig_import_helper()
    del swig_import_helper
else:
    import _RasterToolkit
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_RasterToolkit.NOZONE_swigconstant(_RasterToolkit)
NOZONE = _RasterToolkit.NOZONE
class Cell(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cell, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Cell, name)
    __repr__ = _swig_repr
    __swig_setmethods__["c"] = _RasterToolkit.Cell_c_set
    __swig_getmethods__["c"] = _RasterToolkit.Cell_c_get
    if _newclass:
        c = _swig_property(_RasterToolkit.Cell_c_get, _RasterToolkit.Cell_c_set)
    __swig_setmethods__["r"] = _RasterToolkit.Cell_r_set
    __swig_getmethods__["r"] = _RasterToolkit.Cell_r_get
    if _newclass:
        r = _swig_property(_RasterToolkit.Cell_r_get, _RasterToolkit.Cell_r_set)
    __swig_setmethods__["z"] = _RasterToolkit.Cell_z_set
    __swig_getmethods__["z"] = _RasterToolkit.Cell_z_get
    if _newclass:
        z = _swig_property(_RasterToolkit.Cell_z_get, _RasterToolkit.Cell_z_set)

    def __init__(self, col, row, zone):
        this = _RasterToolkit.new_Cell(col, row, zone)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _RasterToolkit.delete_Cell
    __del__ = lambda self: None
Cell_swigregister = _RasterToolkit.Cell_swigregister
Cell_swigregister(Cell)

class Zone(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Zone, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Zone, name)
    __repr__ = _swig_repr
    __swig_setmethods__["id"] = _RasterToolkit.Zone_id_set
    __swig_getmethods__["id"] = _RasterToolkit.Zone_id_get
    if _newclass:
        id = _swig_property(_RasterToolkit.Zone_id_get, _RasterToolkit.Zone_id_set)
    __swig_setmethods__["cells"] = _RasterToolkit.Zone_cells_set
    __swig_getmethods__["cells"] = _RasterToolkit.Zone_cells_get
    if _newclass:
        cells = _swig_property(_RasterToolkit.Zone_cells_get, _RasterToolkit.Zone_cells_set)

    def __init__(self, zid):
        this = _RasterToolkit.new_Zone(zid)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _RasterToolkit.delete_Zone
    __del__ = lambda self: None
Zone_swigregister = _RasterToolkit.Zone_swigregister
Zone_swigregister(Zone)

class Ward(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Ward, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Ward, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cells"] = _RasterToolkit.Ward_cells_set
    __swig_getmethods__["cells"] = _RasterToolkit.Ward_cells_get
    if _newclass:
        cells = _swig_property(_RasterToolkit.Ward_cells_get, _RasterToolkit.Ward_cells_set)

    def __init__(self):
        this = _RasterToolkit.new_Ward()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _RasterToolkit.delete_Ward
    __del__ = lambda self: None
Ward_swigregister = _RasterToolkit.Ward_swigregister
Ward_swigregister(Ward)


def DevCompare(iRas1, iRas2, result):
    return _RasterToolkit.DevCompare(iRas1, iRas2, result)
DevCompare = _RasterToolkit.DevCompare

def IRasterCompare(iRas1, iRas2, result):
    return _RasterToolkit.IRasterCompare(iRas1, iRas2, result)
IRasterCompare = _RasterToolkit.IRasterCompare

def DRasterCompare(dRas1, dRas2, result):
    return _RasterToolkit.DRasterCompare(dRas1, dRas2, result)
DRasterCompare = _RasterToolkit.DRasterCompare

def IRasterFixNoDataVal(srcRas, srcVal):
    return _RasterToolkit.IRasterFixNoDataVal(srcRas, srcVal)
IRasterFixNoDataVal = _RasterToolkit.IRasterFixNoDataVal

def IRasterSetNoDataToRef(srcRas, refRas):
    return _RasterToolkit.IRasterSetNoDataToRef(srcRas, refRas)
IRasterSetNoDataToRef = _RasterToolkit.IRasterSetNoDataToRef

def DRasterFixNoDataVal(srcRas, srcVal):
    return _RasterToolkit.DRasterFixNoDataVal(srcRas, srcVal)
DRasterFixNoDataVal = _RasterToolkit.DRasterFixNoDataVal

def DRasterSetNoDataToRef(srcRas, refRas):
    return _RasterToolkit.DRasterSetNoDataToRef(srcRas, refRas)
DRasterSetNoDataToRef = _RasterToolkit.DRasterSetNoDataToRef

def DRasterTidyNoDataVal(srcRas, srcVal):
    return _RasterToolkit.DRasterTidyNoDataVal(srcRas, srcVal)
DRasterTidyNoDataVal = _RasterToolkit.DRasterTidyNoDataVal

def IRasterMaskedAddValue(zoneIDRas, val):
    return _RasterToolkit.IRasterMaskedAddValue(zoneIDRas, val)
IRasterMaskedAddValue = _RasterToolkit.IRasterMaskedAddValue

def IRasterNotBoolean(srcRas):
    return _RasterToolkit.IRasterNotBoolean(srcRas)
IRasterNotBoolean = _RasterToolkit.IRasterNotBoolean

def IRasterAddBoolean(ras1Str, ras2Str, resultStr):
    return _RasterToolkit.IRasterAddBoolean(ras1Str, ras2Str, resultStr)
IRasterAddBoolean = _RasterToolkit.IRasterAddBoolean

def Standardise(srcRas, maskRas):
    return _RasterToolkit.Standardise(srcRas, maskRas)
Standardise = _RasterToolkit.Standardise

def RevPolarityStandardise(srcRas, maskRas):
    return _RasterToolkit.RevPolarityStandardise(srcRas, maskRas)
RevPolarityStandardise = _RasterToolkit.RevPolarityStandardise

def AreaFromRaster(wardIDRas, numWards, wardDataRas, refVal, areaOutput):
    return _RasterToolkit.AreaFromRaster(wardIDRas, numWards, wardDataRas, refVal, areaOutput)
AreaFromRaster = _RasterToolkit.AreaFromRaster

def BooleanDownsampler(inputRas, outputRas, singleDimCellsToCell, twoDimCellThreshold):
    return _RasterToolkit.BooleanDownsampler(inputRas, outputRas, singleDimCellsToCell, twoDimCellThreshold)
BooleanDownsampler = _RasterToolkit.BooleanDownsampler

def DRasterSumRows(inputRas, outputCSV):
    return _RasterToolkit.DRasterSumRows(inputRas, outputCSV)
DRasterSumRows = _RasterToolkit.DRasterSumRows

def DRasterSumColumns(inputRas, outputCSV):
    return _RasterToolkit.DRasterSumColumns(inputRas, outputCSV)
DRasterSumColumns = _RasterToolkit.DRasterSumColumns

def DRasterAscToBin(input, output, pathToBinaryConfig):
    return _RasterToolkit.DRasterAscToBin(input, output, pathToBinaryConfig)
DRasterAscToBin = _RasterToolkit.DRasterAscToBin

def DRasterAscToCsv(input, output):
    return _RasterToolkit.DRasterAscToCsv(input, output)
DRasterAscToCsv = _RasterToolkit.DRasterAscToCsv

def IRasterAscToBin(input, output, pathToBinaryConfig):
    return _RasterToolkit.IRasterAscToBin(input, output, pathToBinaryConfig)
IRasterAscToBin = _RasterToolkit.IRasterAscToBin

def IRasterAscToCsv(input, output):
    return _RasterToolkit.IRasterAscToCsv(input, output)
IRasterAscToCsv = _RasterToolkit.IRasterAscToCsv

def DRasterBinToAsc(input, output, hdrFile):
    return _RasterToolkit.DRasterBinToAsc(input, output, hdrFile)
DRasterBinToAsc = _RasterToolkit.DRasterBinToAsc

def DRasterCsvToAsc(input, output, hdrfile):
    return _RasterToolkit.DRasterCsvToAsc(input, output, hdrfile)
DRasterCsvToAsc = _RasterToolkit.DRasterCsvToAsc

def IRasterBinToAsc(input, output, hdrFile):
    return _RasterToolkit.IRasterBinToAsc(input, output, hdrFile)
IRasterBinToAsc = _RasterToolkit.IRasterBinToAsc

def IRasterCsvToAsc(input, output, hdrfile):
    return _RasterToolkit.IRasterCsvToAsc(input, output, hdrfile)
IRasterCsvToAsc = _RasterToolkit.IRasterCsvToAsc

def DRasterAscToODVal(inputRas, inputZoneCodes, outputCSV):
    return _RasterToolkit.DRasterAscToODVal(inputRas, inputZoneCodes, outputCSV)
DRasterAscToODVal = _RasterToolkit.DRasterAscToODVal

def DRasterSubRaster(inRasStr, inCodeStr, outRasStr, outCodeStr, outHdrFile):
    return _RasterToolkit.DRasterSubRaster(inRasStr, inCodeStr, outRasStr, outCodeStr, outHdrFile)
DRasterSubRaster = _RasterToolkit.DRasterSubRaster
# This file is compatible with both classic and new-style classes.


