# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_CellularModel', [dirname(__file__)])
        except ImportError:
            import _CellularModel
            return _CellularModel
        if fp is not None:
            try:
                _mod = imp.load_module('_CellularModel', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _CellularModel = swig_import_helper()
    del swig_import_helper
else:
    import _CellularModel
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class CellularModel(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CellularModel, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CellularModel, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _CellularModel.new_CellularModel()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _CellularModel.delete_CellularModel
    __del__ = lambda self: None

    def Setup(self, wards, res, cols, rows):
        return _CellularModel.CellularModel_Setup(self, wards, res, cols, rows)

    def UseBinaryRasters(self, useBin):
        return _CellularModel.CellularModel_UseBinaryRasters(self, useBin)

    def SetRasterHeader(self, hdr):
        return _CellularModel.CellularModel_SetRasterHeader(self, hdr)

    def SetPathToBinaryConfigFiles(self, binConfigPath):
        return _CellularModel.CellularModel_SetPathToBinaryConfigFiles(self, binConfigPath)

    def LoadWardLabels(self, label, labelColumn, numColumns):
        return _CellularModel.CellularModel_LoadWardLabels(self, label, labelColumn, numColumns)

    def LoadCurrentPopulation(self, popData, curPopColumn, numColumns):
        return _CellularModel.CellularModel_LoadCurrentPopulation(self, popData, curPopColumn, numColumns)

    def LoadFuturePopulation(self, popData, futPopColumn, numColumns):
        return _CellularModel.CellularModel_LoadFuturePopulation(self, popData, futPopColumn, numColumns)

    def LoadWardDensity(self, densityData, densityColumn, numColumns):
        return _CellularModel.CellularModel_LoadWardDensity(self, densityData, densityColumn, numColumns)

    def LoadWardIDRaster(self, iWardIDData):
        return _CellularModel.CellularModel_LoadWardIDRaster(self, iWardIDData)

    def LoadZoneIDRaster(self, zoneIDData):
        return _CellularModel.CellularModel_LoadZoneIDRaster(self, zoneIDData)

    def LoadZoneAVGRaster(self, zoneAVGData):
        return _CellularModel.CellularModel_LoadZoneAVGRaster(self, zoneAVGData)

    def LoadDevLandRaster(self, devLandData):
        return _CellularModel.CellularModel_LoadDevLandRaster(self, devLandData)

    def LoadCellSuitRaster(self, cellSuitData):
        return _CellularModel.CellularModel_LoadCellSuitRaster(self, cellSuitData)

    def SetupFinalDevRaster(self):
        return _CellularModel.CellularModel_SetupFinalDevRaster(self)

    def RunModel(self):
        return _CellularModel.CellularModel_RunModel(self)

    def OutputRasterResult(self, rasterData):
        return _CellularModel.CellularModel_OutputRasterResult(self, rasterData)

    def WriteOverflowWards(self, overflowData):
        return _CellularModel.CellularModel_WriteOverflowWards(self, overflowData)

    def Cleanup(self):
        return _CellularModel.CellularModel_Cleanup(self)
CellularModel_swigregister = _CellularModel.CellularModel_swigregister
CellularModel_swigregister(CellularModel)

# This file is compatible with both classic and new-style classes.


