name: build

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install swig (windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install swig -y

    - name: Build and install openudm
      run: |
        python setup.py build
        python setup.py develop

    - name: Run script
      run: |
        python -m openudm

    - name: Build wheels (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: RalfG/python-wheels-manylinux-build@v0.3.3
      with:
        python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38'
        system-packages: 'swig'

    - name: Build wheels (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pip install setuptools wheel
        python setup.py sdist bdist_wheel

    - name: Publish
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        python setup.py sdist bdist_wheel
        twine upload dist/*
